spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
    include:
      - db
      - security

server:
  port: 8080

logging:
  level:
    org.springframework.orm.jpa: trace
    org.springframework.transaction: trace



