version: '3.1'
services:
  mysql-db:
    image: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  docker-jpa:
    image: elgunsh/spring-data-jpa:0.0.1
    restart: always
    environment:
      DB_CONNECTION_IP: mysql-db
    ports:
      - "8080:8080"
#  nginx:
#    image: gun123/ngnix-docker:0
#    restart: always
#    ports:
#      - 7071:7070
#    depends_on:
#      - docker-common-1
#      - docker-common-2

volumes:
  db: